export const actionTypes = {
  setPopularMovies: 'SET_POPULAR_MOVIES',
  setMostRatedMovies: 'SET_MOST_RATED_MOVIES',
  setUpcomingMovies: 'SET_UPCOMING_MOVIES',
  setNowPlayingMovies: 'SET_NOW_PLAYING_MOVIES',
  setMovieDetails: 'SET_MOVIE_DETAILS',
  setTrailersMovie: 'SET_TRAILERS_MOVIE',
  setMoviesSearched: 'SET_MOVIES_SEARCHED',
  setIsLoading: 'SET_IS_LOADING',
  setLoadingTrailers: 'SET_LOADING_TRAILERS',
  setShowData: 'SET_SHOW_DATA',
  setError: 'SET_ERROR',
  setValueSearcher: 'SET_VALUE_SEARCHER',
  setFilter: 'SET_FILTER',
};
